import { useEffect, useState } from 'react'
import { ArrowUpRight, Check, CheckCircle2, Copy, FileSearch, Fingerprint, Layers3, LockKeyhole, ScanLine, Shield, ShieldCheck, Terminal, X, AlertTriangle, ChevronRight, Workflow } from 'lucide-react'
import type { ReactNode, CSSProperties } from 'react'
import type { Decision, SecurityEvent } from '../types/api'
import { decisionLabel, riskLevel, riskTone, time } from '../utils/format'

export function Brand({ small = false }: { small?: boolean }) { return <span className={`brand-mark ${small ? 'small' : ''}`} aria-hidden="true"><svg viewBox="0 0 40 44" fill="none"><path d="M20 3 35 9v13c0 9-8 15-15 19C13 37 5 31 5 22V9z" stroke="currentColor" strokeWidth="1.6"/><path d="m12 29 8-17 8 17m-12-7h8" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"/></svg></span> }
export const engineIcons = [Fingerprint, FileSearch, Layers3, LockKeyhole]
export function Badge({ decision, compact = false }: { decision: Decision | 'ERROR' | 'IDLE'; compact?: boolean }) { return <span className={`badge ${decision.toLowerCase()} ${compact ? 'compact' : ''}`}><span className="status-dot"/>{decisionLabel(decision)}</span> }
export function Eyebrow({ children }: { children: ReactNode }) { return <div className="eyebrow">{children}</div> }
export function PageHeading({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: ReactNode }) { return <div className="page-heading"><div><Eyebrow>{eyebrow}</Eyebrow><h1>{title}</h1><p>{description}</p></div>{action && <div className="heading-action">{action}</div>}</div> }
export function PanelHeader({ title, icon, extra, subtitle }: { title: string; icon?: ReactNode; extra?: ReactNode; subtitle?: string }) { return <div className="panel-header"><div><h2>{icon}{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{extra}</div> }
export function Empty({ title, text, action, icon = <ScanLine size={23}/> }: { title: string; text: string; action?: ReactNode; icon?: ReactNode }) { return <div className="empty-state"><span className="empty-icon">{icon}</span><h3>{title}</h3><p>{text}</p>{action}</div> }
export function RiskBar({ value, label = true }: { value: number; label?: boolean }) { const tone = riskTone(value); return <div className={`risk-meter ${tone}`}>{label && <div className="risk-label"><span>{riskLevel(value)} risk</span><strong>{value}<small> / 100</small></strong></div>}<div className="risk-track"><div style={{ width: `${Math.min(100, Math.max(0, value))}%` }}/></div></div> }
export function RiskChart({ values, height = 120 }: { values: number[]; height?: number }) {
  const w = 500, h = 100, pad = 18
  const points = values.map((value, i) => ({ x: pad + i * (w - pad * 2) / Math.max(values.length - 1, 1), y: h - 10 - value * .72 }))
  const line = points.map(p => `${p.x},${p.y}`).join(' ')
  return <div className="risk-chart" style={{ height }}><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label={values.length ? `Session risk by turn: ${values.join(', ')}` : 'No session risk data yet'} preserveAspectRatio="none"><defs><linearGradient id="risk-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#b7e4c0" stopOpacity=".16"/><stop offset="1" stopColor="#b7e4c0" stopOpacity="0"/></linearGradient></defs>{[20, 55, 90].map(y => <line key={y} x1="0" x2={w} y1={y} y2={y} stroke="currentColor" strokeDasharray="3 6"/>)}{points.length > 1 && <><polygon points={`${points[0].x},100 ${line} ${points.at(-1)!.x},100`} fill="url(#risk-fill)"/><polyline points={line} fill="none" stroke="#b7e4c0" strokeWidth="2" vectorEffect="non-scaling-stroke"/></>}{points.map((p, i) => <circle key={i} cx={p.x} cy={p.y} r="3.2" fill={values[i] >= 65 ? '#f48d8d' : '#b7e4c0'} stroke="#17201b" strokeWidth="3" vectorEffect="non-scaling-stroke"/>)}</svg>{!values.length && <span className="chart-placeholder">Your session will draw the signal.</span>}</div>
}
export function CopyButton({ text, label = 'Copy result' }: { text: string; label?: string }) {
  const [copied, setCopied] = useState(false), [failed, setFailed] = useState(false)
  useEffect(() => { if (!copied && !failed) return; const timer = window.setTimeout(() => { setCopied(false); setFailed(false) }, 1800); return () => clearTimeout(timer) }, [copied, failed])
  return <button className="button quiet small-button" onClick={async () => { try { await navigator.clipboard.writeText(text); setCopied(true) } catch { setFailed(true) } }} title={label}>{copied ? <Check size={14}/> : <Copy size={14}/>}<span>{copied ? 'Copied' : failed ? 'Copy unavailable' : label}</span></button>
}
export function Pipeline({ busy = false, complete = false, blocked = false, compact = false }: { busy?: boolean; complete?: boolean; blocked?: boolean; compact?: boolean }) {
  const stages = [{ label: 'Normalize', Icon: ScanLine }, { label: 'Decode', Icon: Fingerprint }, { label: 'Context', Icon: FileSearch }, { label: 'Session', Icon: Layers3 }, { label: 'Guard', Icon: ShieldCheck }]
  return <div className={`pipeline ${busy ? 'is-running' : ''} ${compact ? 'compact-pipeline' : ''}`}><div className="pipeline-line"/>{stages.map(({ label, Icon }, i) => <div className="pipeline-step" key={label} style={{ '--step': i } as CSSProperties}><div className="pipeline-node"><Icon size={compact ? 18 : 23}/>{busy && <span className="processing-ring"/>}</div><span>{label}</span><small>{busy ? 'Inspecting…' : 'Inspection layer'}</small></div>)}<div className={`pipeline-step final ${complete ? blocked ? 'rejected' : 'cleared' : ''}`}><div className="pipeline-node"><Shield size={compact ? 18 : 23}/></div><span>Decision</span><small>{complete ? 'Result received' : 'Shared policy'}</small></div></div>
}
export function Processing({ busy }: { busy: string }) { return <div className="processing-panel" role="status" aria-live="polite"><div className="processing-head"><span className="spinner"/><strong>{busy === 'chat' ? 'Screening the conversation' : 'Inspecting your prompt'}</strong><span className="mono">REQUEST PENDING</span></div><Pipeline busy compact/><p>Illustrative inspection flow · awaiting the backend’s completed response.</p></div> }
export function ErrorNotice({ message, onClose }: { message: string; onClose: () => void }) { return <div className="error-notice" role="alert"><AlertTriangle size={18}/><span>{message}</span><button aria-label="Dismiss error" onClick={onClose}><X size={16}/></button></div> }
export function EventList({ events, onSelect, compact = false }: { events: SecurityEvent[]; onSelect?: (e: SecurityEvent) => void; compact?: boolean }) { return <div className={`event-list ${compact ? 'compact-events' : ''}`}>{events.map(event => <button key={event.id} className="event-row" disabled={!onSelect || !event.result} onClick={() => onSelect?.(event)}><span className={`event-glyph ${event.decision.toLowerCase()}`}>{event.decision === 'BLOCK' ? <Shield size={15}/> : event.decision === 'REVIEW' ? <FileSearch size={15}/> : <CheckCircle2 size={15}/>}</span><span className="event-copy"><strong>{event.engine}<Badge decision={event.decision} compact/></strong><span>{event.detail}</span></span><span className="event-meta"><time>{time(event.time)}</time>{event.risk !== null && <span className={`tone-${riskTone(event.risk)}`}>{event.risk} risk</span>}</span>{onSelect && event.result && <ChevronRight size={14}/>}</button>)}</div> }
export function LearningNote({ children }: { children: ReactNode }) { return <div className="learning-note"><Terminal size={15}/><span>{children}</span></div> }
export function LinkButton({ children, onClick }: { children: ReactNode; onClick: () => void }) { return <button className="text-button" onClick={onClick}>{children}<ArrowUpRight size={14}/></button> }
export function Skeleton() { return <div className="skeleton-block" aria-label="Loading"><span/><span/><span/></div> }
export function ArchitectureStamp() { return <span className="architecture-stamp"><Workflow size={12}/> FOUR LAYERS · ONE POLICY</span> }
