export type Decision = 'ALLOW' | 'WARN' | 'REVIEW' | 'SAFE_ANALYSIS' | 'BLOCK'
export type Page = 'Overview' | 'Live Analyzer' | 'Attack Lab' | 'Session Shield' | 'Event Stream' | 'Findings'
export interface GuardResult { ok: boolean; allowed: boolean | null; flags: string[]; status: string | null; checks?: Record<string, { ran: boolean; flagged: boolean; confidence?: string }>; request_id?: string | null; latency_ms?: number | null; error?: string | null; retry_after?: number | null }
export interface Finding { source: string; category: string; severity: string; confidence: number; description: string; evidence: { transformations?: { type: string; before?: string; after?: string }[]; representations?: { type: string; depth: number; decoded_chars: number }[]; flags?: string[] } }
export interface Context { context_type: string; quoted_content_detected: boolean; execution_intent: boolean; analysis_intent: boolean; reason: string; confidence: number }
export interface SessionState { session_id: string; risk_score: number; suspicious_turns: number; turns_considered: number; detected_intent_fragments: string[]; prior_transformations: string[]; risk_trajectory: number[]; last_activity: number; security_summary: string }
export interface AthenaResult { request_id: string; decision: Decision; risk_score: number; original_text: string; normalized_variants: string[]; decoded_variants: string[]; findings: Finding[]; context: Context; guard_result: GuardResult; guard_results: GuardResult[]; session: SessionState; latency_ms: number; permitted: boolean }
export interface Comparison { guard_only: GuardResult; athena: AthenaResult }
export interface ChatResult { stage: 'delivered' | 'prompt_blocked' | 'review_required' | 'response_blocked' | 'llm_error'; answer: string | null; error?: string; session_id: string; prompt_check: AthenaResult; response_check?: { decision: Decision; blocked: boolean; risk_score: number; request_id: string; reasons: string[]; categories: string[]; guard: GuardResult } }
export interface SecurityEvent { id: string; time: number; decision: Decision; risk: number | null; engine: string; categories: string[]; detail: string; latency?: number; result?: AthenaResult; origin: 'browser' | 'server' }
export interface AuditEvent { ts: string; kind: string; decision: string; flags: string[]; audit?: { request_id: string; decision: Decision; risk_score: number; categories: string[]; athena_latency_ms: number } }
export interface Preset { id: string; label: string; finding: number; note: string; turns: string[]; simulate_partial?: boolean }
export interface HealthState { backend: 'checking' | 'online' | 'offline'; guard: 'checking' | 'online' | 'offline' | 'unconfigured'; ready: boolean; missing: string[]; checkedAt?: number }
