import { ArrowUpRight, Check, ChevronDown, Fingerprint, FileSearch, Layers3, ScanLine, ShieldCheck } from 'lucide-react'
import { scenarios } from '../data/demoScenarios'
import { ArchitectureStamp, Brand, Eyebrow, PageHeading, Pipeline } from '../components/ui'

const evidence = [
  { headline: 'Same instruction. A different surface.', problem: 'The recorded Guard tests blocked the plaintext instruction but allowed spaced, hyphenated, underscored and leetspeak variants.', solution: 'Reconstruct selected instruction words in analysis copies and screen both the original and normalized text.', example: 'I-g-n-o-r-e → ignore', ids: '1220112867b2 · 9c54743174cd · db006d6ce8e7 · d0e87cbeeadd', limit: 'Zero-width, full-width and several other transformations were correctly blocked in the same transcript.' },
  { headline: 'An example is not always an instruction.', problem: 'Research explanations and classification requests quoting an injection were blocked as though they were active attacks.', solution: 'Examine quote boundaries and surrounding intent. Injection-only analytical disputes become REVIEW, holding execution.', example: '“Explain why…” → analysis intent → REVIEW', ids: '1fc450d792b7 · 5e6b1040dd1d · c6679ee6601a', limit: 'REVIEW does not automatically allow a completion. Other dangerous findings still block the request.' },
  { headline: 'Meaning can emerge between messages.', problem: 'The transcript allowed a remembered verb, a remembered phrase, and the instruction to combine them as three individual checks.', solution: 'Retain bounded security memory, recognize instruction assembly, and track risk across the session.', example: '“ignore” + “previous instructions” → override', ids: '8b0e40cbd886 · 88ec9703ade9 · 46bcd912c3fb', limit: 'This is an architectural finding. It does not alone demonstrate that an LLM executed the assembled instruction.' },
  { headline: 'Make encoded meaning inspectable.', problem: 'Earlier teammate experiments recorded encoded bypasses. Newer Base64, hex and URL examples were correctly blocked by the Guard.', solution: 'Decode common representations safely, apply size and recursion limits, and inspect the revealed content with the same policy.', example: 'Encoded text → decoded data → security inspection', ids: 'Historical teammate notes + attack_tests.md', limit: 'Results depend on the exact payload. The live comparator reports the current verdict without assuming a bypass.' },
]
const icons = [ScanLine, FileSearch, Layers3, Fingerprint]
export default function Findings({ tryScenario }: { tryScenario: (id: string) => void }) { return <><PageHeading eyebrow="RESEARCH & FINDINGS" title="Four findings. A stronger boundary." description="What the team observed, what we built, and what the evidence actually supports." action={<span className="subtle-pill"><ShieldCheck size={13}/>SecureAI Hackathon · Challenge 3</span>}/><div className="findings-intro panel"><div><Brand/><div><Eyebrow>ATHENA SHIELD</Eyebrow><h2>Reveal. Understand. Remember. Protect.</h2><p>An additional layer around SecureAI Guard, built on the team’s original Model Armor.</p></div></div><ArchitectureStamp/><Pipeline compact/></div><div className="findings-grid">{scenarios.map((s, i) => { const e = evidence[i], Icon = icons[i]; return <article className="panel research-card" key={s.id}><div className="research-top"><span className="research-number">{s.number}</span><span className={`evidence-status ${s.evidenceType}`}>{s.evidence}</span></div><div className="research-title"><Icon size={22}/><h2>{s.title}</h2></div><h3>{e.headline}</h3><p>{e.problem}</p><div className="research-solution"><Eyebrow><Check size={12}/> {s.engine.toUpperCase()}</Eyebrow><p>{e.solution}</p><code>{e.example}</code></div><details className="research-evidence"><summary>Evidence & scope<ChevronDown size={14}/></summary><p>{e.limit}</p><span className="mono tiny">{e.ids}</span></details><button className="text-button" onClick={() => tryScenario(s.id)}>Explore in Attack Lab<ArrowUpRight size={14}/></button></article> })}</div><div className="research-footer"><ShieldCheck size={16}/><p><strong>Defense in depth, with clear limits.</strong> These are observed cases and tested defenses. Heuristic detection does not cover every semantic attack. Incomplete screening holds execution.</p></div></> }
