import { ArrowDownLeft, ArrowUpRight, ArrowRight, Fingerprint, FileSearch, Layers3, LockKeyhole, Radio, Shield, ShieldCheck, Sparkles, Activity } from 'lucide-react'
import type { ConsoleState } from '../hooks/useConsole'
import type { Page, SecurityEvent } from '../types/api'
import { ArchitectureStamp, Brand, Empty, EventList, Eyebrow, LinkButton, PageHeading, PanelHeader, Pipeline, RiskBar, RiskChart } from '../components/ui'

export default function Overview({ state: s, navigate, inspectEvent }: { state: ConsoleState; navigate: (p: Page) => void; inspectEvent: (e: SecurityEvent) => void }) {
  const actualThreats = s.events.filter(e => e.decision === 'BLOCK' && e.categories.some(c => ['injection', 'session_injection', 'secret_leak', 'guard_flag'].includes(c))).length
  const metrics = [
    { title: 'Threats blocked', value: actualThreats, note: 'Detected threats in this workspace', Icon: Shield, tone: 'green' },
    { title: 'Obfuscations detected', value: s.events.filter(e => e.categories.some(c => ['obfuscation', 'encoding'].includes(c))).length, note: 'Revealed representations', Icon: Fingerprint, tone: 'blue' },
    { title: 'Session escalations', value: s.events.filter(e => e.categories.includes('session_injection')).length, note: 'Risk connected across turns', Icon: Layers3, tone: 'amber' },
    { title: 'Analysis recognized', value: s.events.filter(e => ['REVIEW', 'SAFE_ANALYSIS'].includes(e.decision)).length, note: 'Review or safe-analysis decisions', Icon: FileSearch, tone: 'purple' },
  ]
  const session = s.turns.at(-1)?.athena.session
  return <>
    <PageHeading eyebrow="SECURITY OVERVIEW" title="Clarity is your strongest defense." description="Protecting meaning across representations, context, and conversations." action={<button className="button primary" onClick={() => navigate('Live Analyzer')}><Sparkles size={16}/>Open analyzer<ArrowUpRight size={16}/></button>}/>
    <div className="section-overline"><span><span className="tiny-dot"/>CURRENT BROWSER SESSION</span><span>{s.events.length} screening events</span></div>
    <div className="metrics-grid">{metrics.map(({ title, value, note, Icon, tone }) => <div className="metric-card" key={title}><div className="metric-top"><span>{title}</span><span className={`metric-icon ${tone}`}><Icon size={17}/></span></div><strong className="metric-value">{String(value).padStart(2, '0')}</strong><div className="metric-note"><span className={`mini-dash ${tone}`}/>{note}</div></div>)}</div>
    <div className="overview-main"><section className="panel architecture-panel"><div className="architecture-backdrop" aria-hidden="true"><div/><div/><div/></div><div className="architecture-top"><span className="subtle-pill green-pill"><ShieldCheck size={12}/>DEFENSE IN DEPTH</span><ArchitectureStamp/></div><div className="architecture-copy"><h2>One prompt.<br/><span>Four perspectives.</span></h2><p>Reveal hidden instructions. Recognize intent.<br/>Keep the whole conversation in view.</p></div><div className="architecture-emblem" aria-hidden="true"><div className="emblem-orbit outer"/><div className="emblem-orbit inner"/><div className="emblem-core"><Brand/></div><span className="orbit-dot first"/><span className="orbit-dot second"/></div><Pipeline/><div className="architecture-bottom"><span><LockKeyhole size={12}/>Incomplete checks hold execution.</span><LinkButton onClick={() => navigate('Findings')}>Explore the architecture</LinkButton></div></section>
      <section className="panel protection-panel"><PanelHeader title="Protection status" icon={<ShieldCheck size={16}/>} extra={<span className="mono tiny muted">04 ENGINES</span>}/><div className="engine-statuses">{[{ name: 'Encoding Shield', Icon: Fingerprint }, { name: 'Normalization Shield', Icon: Activity }, { name: 'Context Adjudicator', Icon: FileSearch }, { name: 'Session Shield', Icon: Layers3 }].map(({ name, Icon }) => <div key={name}><span className="engine-icon"><Icon size={16}/></span><span>{name}</span><span className={`engine-state ${s.health.backend === 'online' ? 'available' : ''}`}><i/>{s.health.backend === 'online' ? 'Available' : s.health.backend === 'checking' ? 'Checking' : 'Offline'}</span></div>)}</div><div className="guard-connection"><Shield size={15}/><span>SecureAI Guard</span><span className={s.health.guard === 'online' ? 'tone-green' : 'tone-amber'}>{s.health.guard === 'online' ? 'Connected' : s.health.guard === 'unconfigured' ? 'Needs setup' : s.health.guard === 'checking' ? 'Checking' : 'Unavailable'}</span></div><div className="current-risk"><Eyebrow>SESSION SHIELD RISK</Eyebrow>{session ? <RiskBar value={session.risk_score}/> : <><div className="risk-label"><span className="muted">Awaiting first turn</span><strong>—<small> / 100</small></strong></div><div className="risk-track"/></>}<div className="risk-scale"><span>LOW</span><span>MODERATE</span><span>HIGH</span><span>CRITICAL</span></div></div></section>
    </div>
    <div className="overview-bottom"><section className="panel activity-panel"><PanelHeader title="Live security activity" icon={<Radio size={16}/>} extra={<LinkButton onClick={() => navigate('Event Stream')}>View stream</LinkButton>}/>{s.events.length ? <EventList events={s.events.slice(0, 5)} onSelect={inspectEvent} compact/> : <Empty title="A quiet workspace. A ready defense." text="Your analyses will appear here as they happen." action={<button className="button secondary small-button" onClick={() => navigate('Attack Lab')}>Run your first scenario<ArrowRight size={14}/></button>}/>}<div className="panel-bottom-note"><span className="tiny-dot"/>Real requests. Real decisions. No generated alerts.</div></section><section className="panel session-preview"><PanelHeader title="The conversation matters" icon={<Layers3 size={16}/>} extra={<ArrowDownLeft size={17} className="muted"/>}/><p>Individually harmless fragments can tell<br/>a different story together.</p><RiskChart values={s.turns.map(t => t.athena.session.risk_score)}/><div className="session-preview-bottom"><span className="mono tiny muted">{s.turns.length} TURNS INSPECTED</span><LinkButton onClick={() => navigate('Session Shield')}>Open session</LinkButton></div></section></div>
  </>
}
