import { useEffect, useState } from 'react'
import { ArrowRight, ChevronRight, Layers3, MessageSquare, RotateCcw, Send, Shield, Terminal } from 'lucide-react'
import type { ConsoleState } from '../hooks/useConsole'
import { sessionSteps } from '../data/demoScenarios'
import { guardDecision, time } from '../utils/format'
import { Badge, CopyButton, Empty, Eyebrow, PageHeading, PanelHeader, RiskBar, RiskChart } from '../components/ui'

export function SessionWorkbench({ state: s }: { state: ConsoleState }) {
  const [input, setInput] = useState(sessionSteps[s.turns.length] || '')
  const latest = s.turns.at(-1)?.athena.session
  useEffect(() => { setInput(sessionSteps[s.turns.length] || '') }, [s.turns.length, s.sessionId])
  return <div className="session-layout"><section className="panel conversation-panel"><PanelHeader title="Conversation simulator" icon={<MessageSquare size={16}/>} extra={<span className="subtle-pill">Synthetic inputs · real checks</span>}/><div className="session-guide"><div className="session-guide-head"><Eyebrow>THREE TURNS. ONE EMERGING INSTRUCTION.</Eyebrow><span>{Math.min(s.turns.length, 3)} / 3</span></div><div className="session-stepper">{['Remember a verb', 'Remember a phrase', 'Combine the fragments'].map((label, i) => <div className={s.turns.length > i ? 'done' : s.turns.length === i ? 'next' : ''} key={label}><span>{String(i + 1).padStart(2, '0')}</span><small>{label}</small>{i < 2 && <ChevronRight size={13}/>}</div>)}</div></div><div className="conversation-log">{s.turns.length ? s.turns.map((t, i) => <div className="conversation-turn" key={t.athena.request_id}><div className="turn-heading"><span className="turn-avatar"><Terminal size={14}/></span><strong>Turn {i + 1}</strong><span className="mono tiny muted">{time(t.athena.session.last_activity * 1000)}</span></div><div className="message-bubble">{t.athena.original_text}</div><div className="turn-verdicts"><div><span>Guard</span><Badge decision={guardDecision(t.guard_only)} compact/></div><ArrowRight size={13}/><div><span>Athena</span><Badge decision={t.athena.decision} compact/></div><span className="mono">Risk {t.athena.session.risk_score}</span></div><p className="turn-reason">{t.athena.findings.find(f => ['high', 'critical', 'medium'].includes(f.severity))?.description || t.athena.findings[0]?.description || 'All required screening checks cleared.'}</p>{!t.athena.permitted && <div className="tiny muted">This turn is held and will not enter executable history.</div>}</div>) : <Empty title="The first message is only the beginning." text="Send each synthetic turn to compare message-level screening with conversation-aware inspection." icon={<Layers3 size={25}/>}/>}</div>{s.busy === 'session' && <div className="session-pending" role="status"><span className="spinner"/>Inspecting current message and retained context…</div>}<div className="session-composer"><label htmlFor="session-input">{s.turns.length < 3 ? `NEXT SYNTHETIC TURN · ${s.turns.length + 1}` : 'CONTINUE THE CONVERSATION'}</label><textarea id="session-input" value={input} onChange={e => setInput(e.target.value)} disabled={!!s.busy} placeholder="Enter another message to inspect…" spellCheck={false}/><div><span className="mono tiny muted">{[...input].length} / 3,999</span><button className="button primary" disabled={!!s.busy || !input.trim() || [...input].length > 3999} onClick={() => void s.sendTurn(input)}><Send size={14}/>{s.turns.length < 3 ? `Send turn ${s.turns.length + 1}` : 'Send turn'}</button></div></div></section>
      <aside className="session-telemetry"><section className="panel"><PanelHeader title="Session security state" icon={<Shield size={16}/>}/><div className="telemetry-body"><Eyebrow>CUMULATIVE RISK</Eyebrow>{latest ? <RiskBar value={latest.risk_score}/> : <div className="telemetry-empty-score">—<small>Waiting for the first response</small></div>}<RiskChart values={s.turns.map(t => t.athena.session.risk_score)} height={130}/><div className="telemetry-stats"><div><span>Turns inspected</span><strong>{s.turns.length}</strong></div><div><span>Suspicious turns</span><strong>{latest?.suspicious_turns ?? '—'}</strong></div><div><span>Last activity</span><strong className="mono">{latest ? time(latest.last_activity * 1000) : '—'}</strong></div></div><div className="fragment-section"><Eyebrow>INTENT FRAGMENTS</Eyebrow>{latest?.detected_intent_fragments.length ? <div className="fragment-tags">{latest.detected_intent_fragments.map((f, i) => <code key={i}>{f}</code>)}</div> : <p className="muted small">No retained instruction fragments.</p>}</div>{latest?.prior_transformations.length ? <div className="fragment-section"><Eyebrow>RECENT TRANSFORMATIONS</Eyebrow>{[...new Set(latest.prior_transformations)].map(t => <span className="tag" key={t}>{t.replaceAll('_', ' ')}</span>)}</div> : null}{latest && <div className="session-summary">{latest.security_summary}</div>}</div><div className="session-reset"><button className="button secondary" disabled={!!s.busy} onClick={() => void s.reset()}><RotateCcw size={14}/>Reset session</button></div></section><div className="session-id"><span className="mono tiny">SESSION / {s.sessionId.slice(-12)}</span><CopyButton text={s.sessionId} label="Copy ID"/></div><p className="telemetry-note">Bounded memory. Decaying risk. Sessions expire after inactivity. Each turn uses the same session ID.</p></aside></div>
}
export default function Session({ state }: { state: ConsoleState }) { return <><PageHeading eyebrow="SESSION SHIELD" title="See the conversation take shape." description="Track intent across turns. Catch the instruction that no single message reveals." action={<span className="subtle-pill"><Layers3 size={13}/>Conversation-aware protection</span>}/><SessionWorkbench state={state}/></> }
