import { useEffect, useState } from 'react'
import { Activity, ArrowUpRight, BookOpen, ChevronRight, CircleHelp, FlaskConical, Layers3, LayoutDashboard, Menu, Radio, ScanLine, ShieldCheck, Terminal, X } from 'lucide-react'
import { useConsole } from './hooks/useConsole'
import type { Page, SecurityEvent } from './types/api'
import { time } from './utils/format'
import { Brand, ErrorNotice } from './components/ui'
import Overview from './pages/Overview'
import Analyzer from './pages/Analyzer'
import AttackLab from './pages/AttackLab'
import Session from './pages/Session'
import Events from './pages/Events'
import Findings from './pages/Findings'

const navigation = [{ page: 'Overview', Icon: LayoutDashboard }, { page: 'Live Analyzer', Icon: ScanLine }, { page: 'Attack Lab', Icon: FlaskConical }, { page: 'Session Shield', Icon: Layers3 }, { page: 'Event Stream', Icon: Radio }, { page: 'Findings', Icon: BookOpen }] as const
const slug = (p: string) => p.toLowerCase().replaceAll(' ', '-')
const initialPage = (): Page => navigation.find(n => slug(n.page) === location.hash.slice(1))?.page || 'Overview'

export default function App() {
  const s = useConsole()
  const [page, setPage] = useState<Page>(initialPage), [text, setText] = useState(''), [lab, setLab] = useState('normalization'), [mobileNav, setMobileNav] = useState(false), [clock, setClock] = useState(Date.now())
  const [help, setHelp] = useState(false)
  useEffect(() => { const timer = window.setInterval(() => setClock(Date.now()), 1000); const update = () => setPage(initialPage()); window.addEventListener('hashchange', update); return () => { clearInterval(timer); window.removeEventListener('hashchange', update) } }, [])
  useEffect(() => { document.title = `${page} · Athena Shield`; window.scrollTo({ top: 0, behavior: 'instant' }) }, [page])
  useEffect(() => { const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') { setHelp(false); setMobileNav(false) } }; document.addEventListener('keydown', onKey); return () => document.removeEventListener('keydown', onKey) }, [])
  function navigate(next: Page) { setPage(next); location.hash = slug(next); setMobileNav(false) }
  function openAnalyzer(value: string) { setText(value); s.clearResult(); navigate('Live Analyzer') }
  function inspectEvent(event: SecurityEvent) { if (!event.result) return; openAnalyzer(event.result.original_text) }
  const backendOnline = s.health.backend === 'online'
  const guardOnline = s.health.guard === 'online'
  return <div className="app-shell"><a className="skip-link" href="#main-content">Skip to content</a>{mobileNav && <button className="sidebar-scrim" aria-label="Close navigation" onClick={() => setMobileNav(false)}/>}
    <aside className={`sidebar ${mobileNav ? 'mobile-open' : ''}`}><a className="brand" href="#overview" onClick={() => navigate('Overview')}><Brand/><span>ATHENA<span>SHIELD<span className="brand-version">/ 02</span></span></span></a><div className="workspace-select"><span className="workspace-avatar"><Terminal size={15}/></span><div><strong>Security workspace</strong><span>Local environment</span></div><ChevronRight size={14}/></div><div className="nav-label">WORKSPACE</div><nav aria-label="Main navigation">{navigation.map(({ page: p, Icon }) => <button key={p} className={page === p ? 'active' : ''} onClick={() => navigate(p)} aria-current={page === p ? 'page' : undefined}><Icon size={18}/><span>{p}</span>{p === 'Attack Lab' && <span className="nav-count">4</span>}{p === 'Live Analyzer' && <span className="nav-shortcut">↗</span>}</button>)}</nav><div className="sidebar-note"><span className="sidebar-note-icon"><ShieldCheck size={18}/></span><strong>Meaning matters.</strong><p>Four layers of perspective.<br/>One informed decision.</p><button onClick={() => navigate('Findings')}>Meet your defenses<ArrowUpRight size={13}/></button></div><div className="sidebar-bottom"><div className="system-status"><span className={`status-led ${backendOnline ? 'online' : s.health.backend === 'checking' ? 'pending' : 'offline'}`}/><span>Athena API</span><small>{backendOnline ? 'Online' : s.health.backend === 'checking' ? 'Checking' : 'Offline'}</small></div><div className="system-status"><span className={`status-led ${guardOnline ? 'online' : 'pending'}`}/><span>SecureAI Guard</span><small>{guardOnline ? 'Connected' : s.health.guard === 'unconfigured' ? 'Not configured' : s.health.guard === 'checking' ? 'Checking' : 'Unavailable'}</small></div><div className="sidebar-footer"><span className="version-label">ATHENA v2.0</span><button className="icon-button" aria-label="Open quick guide" onClick={() => setHelp(true)}><CircleHelp size={16}/></button></div></div></aside>
    <div className="main-shell"><header className="window-bar"><div className="window-left"><button className="mobile-menu icon-button" aria-label="Open navigation" onClick={() => setMobileNav(true)}><Menu size={18}/></button><div className="traffic-lights" aria-hidden="true"><i/><i/><i/></div><span className="window-divider"/><span className="breadcrumb">Workspace<ChevronRight size={13}/><strong>{page}</strong></span></div><div className="window-right"><span className={`connection-pill ${backendOnline ? 'connected' : ''}`}><span className="tiny-dot"/>{backendOnline ? 'API online' : s.health.backend === 'checking' ? 'Connecting' : 'API offline'}</span><span className="mono top-clock">{time(clock)}</span><button className="icon-button help-button" aria-label="Open quick guide" onClick={() => setHelp(true)}><CircleHelp size={17}/></button></div></header>
      <main id="main-content" className="main-content"><div className="workspace-overline"><span><Activity size={13}/>AI SECURITY COMMAND CENTER</span><span>SECUREAI HACKATHON <span className="overline-slash">/</span> CHALLENGE 03</span></div>{s.error && <ErrorNotice message={s.error} onClose={() => s.setError('')}/>}{page === 'Overview' && <Overview state={s} navigate={navigate} inspectEvent={inspectEvent}/>} {page === 'Live Analyzer' && <Analyzer state={s} text={text} setText={setText}/>} {page === 'Attack Lab' && <AttackLab key={lab} state={s} initial={lab} openAnalyzer={openAnalyzer}/>} {page === 'Session Shield' && <Session state={s}/>} {page === 'Event Stream' && <Events state={s} inspectEvent={inspectEvent}/>} {page === 'Findings' && <Findings tryScenario={id => { setLab(id); navigate('Attack Lab') }}/>}<footer className="app-footer"><span><Brand small/>ATHENA SHIELD <span className="footer-separator">/</span> Defense in depth for SecureAI Guard</span><span><span className="tiny-dot"/>Built to see the whole picture.</span></footer></main>
    </div>{help && <div className="modal-backdrop" onClick={() => setHelp(false)}><section className="quick-guide panel" role="dialog" aria-modal="true" aria-labelledby="guide-title" onClick={e => e.stopPropagation()}><button className="icon-button modal-close" aria-label="Close quick guide" autoFocus onClick={() => setHelp(false)}><X size={18}/></button><Brand/><h2 id="guide-title">Your demo, in four moves.</h2><p>Choose a synthetic scenario, then let the evidence tell the story.</p><ol><li><strong>Compare a prompt.</strong> Open Live Analyzer or pick a scenario in Attack Lab.</li><li><strong>Inspect the difference.</strong> See actual Guard and Athena verdicts side by side.</li><li><strong>Reveal the reasoning.</strong> Explore transformations, decoded data, and context.</li><li><strong>Connect the turns.</strong> Send the three Session Shield messages one at a time.</li></ol><div className="guide-note">A missing or incomplete Guard response causes a policy block. REVIEW holds execution. The visual processing sequence is illustrative, not streamed stage telemetry.</div><button className="button primary" onClick={() => { setHelp(false); navigate('Attack Lab') }}>Explore the lab<ArrowRightIcon/></button></section></div>}
  </div>
}
function ArrowRightIcon() { return <ArrowUpRight size={15}/> }
